### ISSUE TITLE
add best solution for aws account

### ISSUE THREAD

**Issue by mehdiraized** [adebayohountondji/strapi-plugin-backup#2]
please add tutorials to create aws account for backups

**Comment by adebayohountondji** [comment]
Hello @mehdiraized,

This plugin assumes that the users have a minimum knowledge about the storage of the provider they decided to configure. Otherwise, there are some useful links below that you can use to create an AWS account and s3 bucket for storage:

- [Getting started: Are you a first-time AWS user?](https://docs.aws.amazon.com/accounts/latest/reference/welcome-first-time-user.html)
- [Create resources (a bucket and an IAM user) in account A and grant permissions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-walkthroughs-managing-access-example1.html#grant-permissions-to-user-in-your-account-step1)

Nevertheless, I am willing to add support for a cloud storage service with which you would be familiar.

Thank you again for your suggestion and your interest in this project.
